name: secrets-gitleaks

 

on:

  push:

  pull_request:

  workflow_dispatch:

 

permissions:

  contents: read

 

jobs:

  gitleaks:

    runs-on: ubuntu-latest

 

    steps:

      - name: Checkout full history

        uses: actions/checkout@v7

        with:

          fetch-depth: 0

 

      - name: Run Gitleaks

        uses: gitleaks/gitleaks-action@v3

        env:

          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

 

          # Arquivo customizado usado no LAB

          GITLEAKS_CONFIG: .gitleaks.toml

 

          # Necessário caso o repositório pertença

          # a uma GitHub Organization:

          #

          # GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
