name: Secret Scanning config file - Gitleaks

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Gitleaks
        continue-on-error: true
        run: |
          docker run --rm \
            -v "$PWD:/repo" \
            ghcr.io/gitleaks/gitleaks:latest \
            git \
            --config /repo/.gitleaks.toml \
            --redact \
            --report-format json \
            --report-path /repo/gitleaks-report.json \
            /repo

      - name: Upload Gitleaks Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks-report.json
          if-no-files-found: error
